baseURL = "https://michimani.github.io/SimpLog" # Normally you don't need to specify a subdirectory
title = "SimpLog"
description = ""
author = "michimani"
copyright = "Copyright © 2021, Hugo Authors; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
googleAnalytics = ""
disqusShortname = "https-michimani-github-io-simplog"
themesDir = "../../" # Delete this line if you want to use this theme on your site
theme = "SimpLog"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 30

  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 40

[taxonomies]
  category = "categories"
  tag = "tags"
  archive = "archives"

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[params]
  subtitle = "simple blog theme"
  colorTheme = "default"
  description = "This is a simple blog theme for Hugo."
  twitter = "michimani210"

  [params.enabled]
    comment = true
